name: Build nightly release

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - id: current_version
        run: echo "::set-output name=version::$(npm pkg get version)"
      - run: rm package-lock.json
      - run: npm --no-git-tag-version version ${{ steps.current_version.outputs.version }}-${{ github.run_number }}-nightly
      - run: npm i
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: package
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_name: Nightly Build ${{ github.run_number }}
          draft: false
          prerelease: true
          files: ./vscode-github-actions-${{ steps.current_version.outputs.version }}-${{ github.run_number }}-nightly.vsix
